server:
  port: 9000


spring:
  application:
    name: gateway-order

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#    sentinel:
#      transport:
#        dashboard: localhost:9999
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#resttemplate:
#  sentinel:
#    enabled: true
